export const FAVOURITE_ADD = 'FAVOURITE_ADD';
export const FAVOURITE_REMOVE = 'FAVOURITE_REMOVE';
export const FAVOURITE_REMOVE_ALL = 'FAVOURITE_REMOVE_ALL';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const PRODUCTS_ADD = 'PRODUCTS_ADD';
export const PRODUCTS_REMOVE = 'PRODUCTS_REMOVE';
